version: "3"

services:
  twitter:
    container_name: twitter
    image: jiuzhang/twitter
    depends_on:
      - mysql8
    tty: true
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - MYSQL_HOST=mysql8
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=twitter

  mysql8:
    image: mysql:8.0
    container_name: mysql8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: twitter
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

